language: python
python:
  - 2.6
  - 2.7
env:
  - PLONE_VERSION=4.1
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3 QA=true
matrix:
  exclude:
    - python: 2.7
      env: PLONE_VERSION=4.1
    - python: 2.6
      env: PLONE_VERSION=4.2
    - python: 2.6
      env: PLONE_VERSION=4.3 QA=true
  allow_failures:
    - python: 2.6
      env: PLONE_VERSION=4.1
    - python: 2.7
      env: PLONE_VERSION=4.2
before_install:
  - sudo apt-get install -y libjpeg-dev libgif-dev libpng-dev libz-dev ghostscript
install:
  - sed -ie "s#test-plone-4.x.cfg#test-plone-$PLONE_VERSION.x.cfg#" travis.cfg
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg -N -q -t 3
script: bin/test
after_success: test -v QA && bin/coverage.sh && pip install -q coveralls && coveralls || true
